# We have to use a separate template to determine the current namespace for the collection. (Templating in values.yaml is not possible)
{{- if not .Values.alloy.alloy.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-alloy
  namespace: {{ .Release.Namespace }}
data:
  config.alloy: |
    loki.source.kubernetes_events "default" {
      forward_to = [loki.process.modify_event_labels.receiver]
      namespaces = ["{{ .Release.Namespace }}"]
      log_format = "json"
    }

    loki.process "modify_event_labels" {
      // Extract "kind" and "type" from log line.
      forward_to = [loki.write.events.receiver]
      stage.json {
        expressions = {"kind" = "", "type" = ""}
      }

      // Set extracted values as loki labels.
      stage.labels {
        values = {
          "kind" = "",
          "level" = "type",
        }
      }
    }

    loki.write "events" {
      endpoint {
        url = "http://k8s-loki-gateway.{{ .Release.Namespace }}.svc.cluster.local/loki/api/v1/push"
        basic_auth {
          username = sys.env("LOKI_USERNAME")
          password = sys.env("LOKI_PASSWORD")
        }
      }
    }

    logging {
      level  = "{{ .Values.logLevel }}"
      format = "json"
    }
{{- end }}
